#!/usr/bin/env perl

#========================================================================
# rmexp-local
#========================================================================

use strict;
use warnings;

use Time::Local;
use POSIX;
use Getopt::Long;
use Pod::Usage;

use FindBin;
use lib "$FindBin::Bin/lib";

use Rmexp::Lib;
use Rmexp::Rmexp;

#use constant {
#    LOG_FILE	=> '/tmp/1s8_expire.log',	# The name of the logfile
#};
#use constant TTY_STDOUT => -t STDOUT;   # is STDOUT connected to tty?
#use constant TTY_STDOUT => 0;
our ( $opt_a, $opt_c, $opt_l, $opt_m, $opt_n, $opt_s, $opt_help, $opt_man );

GetOptions( "a", "d", "c=s", "l", "m", "n", "s", "help|?", "man" )
  || pod2usage(2);
pod2usage( -input => "rmexp.pod", -exitval => 0, -verbose => 2 ) if $opt_man;
#pod2usage( -input => "rmexp.pod", -exitval => 1 ) if ( $opt_help || !$opt_c );
pod2usage(1) if ( $opt_help || !$opt_c );

&ConfigDataRead($opt_c);

my $mounted;
if ($opt_m) {
    $mounted = &mount();
}

my $maxDepth = $Conf{maxDepth} || 255;

&getBackupList( $Conf{backupDir}, 0 );

unless ($opt_l) {
    print "------ Debug ------", "\n", "Performed actions:", "\n" if $opt_d;
    map { &BackupExpire($_) } keys %BackupList;
    print "-------------------", "\n\n" if $opt_d;
}

if ($mounted) {
    system("umount $Conf{mountPoint}");
}

&ShowReport();

exit(0);

sub mount {
    return 0
      if ( grep { / on $Conf{mountPoint} \(/ } qx{/sbin/mount} );
    system("mount $Conf{mountPoint}") == 0
      or die "Can't mount $Conf{mountPoint}\n";
    return 1;
}

sub getBackupList {
    my ( $uncDir, $currDepth ) = @_;

    opendir my $dh, $uncDir
      or die "Can't open directory $uncDir: ", $!, "\n";
    # change die to return

    while ( readdir $dh ) {
        my $name    = $_;
        my $uncFile = "$uncDir/$name";
        if ( -d $uncFile ) {
            next if $name =~ /^[.]{1,2}$/;
            die "*FATAL* Excedeed max directory depth of $maxDepth", "\n"
              if ( $currDepth >= $maxDepth );
            &getBackupList( "$uncDir/$name", $currDepth + 1 );
        }

        next unless ( -f $uncFile );
        next unless $name =~ /^.+$Conf{fileNameSuffix}$/;

        if ( $name =~ /^$Conf{fileNameRE}$Conf{fileNameSuffix}$/ ) {
            my $fileSize = -s $uncFile;

            # Time::Local : months start at 0, years have 1900 subtracted
            my $startTime = timelocal( $7, $6, $5, $4, $3 - 1, $2 - 1900 );

            if ( $BackupList{$1}{$startTime} ) {
                die <<EOF
*FATAL* Duplicate backups:
$BackupList{$1}{$startTime}{dir}/$BackupList{$1}{$startTime}{fileName}
$uncFile
EOF
            }

            $BackupList{$1}{$startTime} = {
                fileName => $name,
                fileSize => $fileSize,
                level    => $8 ? $8 : 0,
                dir      => $uncDir,
            };
        }
        else {
            warn "*WARNING* unknown date/time format in file name: $uncFile\n";
        }
    }
    close $dh;
}

#
# Print report
#
sub ShowReport {

    unless (%BackupList) {
        print POSIX::strftime ( '%Y-%m-%d %H:%M', localtime(time) ), "\n\n";
        print "*WARNING* No backups found!\n";
        return;
    }

    my ( $lastStartTime, @Report );
    my $maxPrefixWidth = my $warnOutdated = 0;

    map {
        my @StartTimes;
        my $name = $_;

        $maxPrefixWidth = length if ( length > $maxPrefixWidth );

        if ($opt_a) {
            @StartTimes = ( sort keys %{ $BackupList{$_} } );
        }
        else {
            # [-1] implies the most recent backup for each host.
            @StartTimes = ( ( sort keys %{ $BackupList{$_} } )[-1] );
        }

        for (@StartTimes) {
            my $startTime = $_;
            $lastStartTime = $startTime;

            push @Report,
              [
                $name,
                $BackupList{$name}{$startTime}->{level},
                $BackupList{$name}{$startTime}->{fileSize} / 1024**2,
                POSIX::strftime( '%Y-%m-%d %H:%M', localtime($startTime) ),
                floor( ( time - $startTime ) / ( 24 * 3600 ) )
              ];
        }
        unless (
            ( time - $lastStartTime ) / (
                24 * 3600 * (
                    ( $Conf{IncrPeriod} //= -1 ) > 0
                    ? $Conf{IncrPeriod}
                    : $Conf{FullPeriod}
                )
            ) < 1
          )
        {
            $warnOutdated = 1;
        }

    } sort keys %BackupList;

    !$opt_s || $warnOutdated || return;

    # Print report header and table header

    print POSIX::strftime ( '%Y-%m-%d %H:%M', localtime(time) ), "\n\n";
    print "Number of hosts: ", scalar( keys %BackupList ), "\n", "\n";

    print "*WARNING* Some backups are outdated!", "\n\n" if $warnOutdated;

    printf "%-${maxPrefixWidth}s | %5s | %9s | %-16s | %8s\n",
      "Hostname", "Level", "Size (MB)", "Last available", "Days old";

    my $i = $maxPrefixWidth + 50;
    while ( $i-- ) { print "-" }
    print "\n";

    # Print rest of the table
    my $reportRow;
    for $reportRow (@Report) {
        printf "%-${maxPrefixWidth}s | %5s | %9.2f | %16s | %8s\n", @$reportRow;
    }
}

sub BackupRemove {
    SmbFileRemove(@_);
}

sub SmbFileRemove {
    my ( $fileName, $client, $startTime ) = @_;
    my $ret;
    my $dir     = $BackupList{$client}{$startTime}{dir};
    my $uncFile = "$dir/$fileName";
    if ($opt_n) {
        $ret = -w $dir
          or warn "Directory $dir is not writable.\n";
    }
    else {
        $ret = unlink $uncFile
          or warn "Can't unlink file $uncFile: ", $!, "\n";
    }
    return $ret ? 0 : 1;
}

#sub log_it {
#print @_, "\n";
#  if (TTY_STDOUT) {     # write to STDOUT if tty connected
#    print @_, "\n";
#  } else {
##    openlog('rmexp', 'pid', 'user');
##    syslog('info', @_);
##    closelog();
#
#    open LOG, '>>', LOG_FILE;
#    print LOG scalar(localtime), ' ', @_, "\n";
#    close LOG || die $!;
#  }
#}

__END__


=head1 SYNOPSIS

B<rmexp-local [-a] [-d] [-n] [-m] [-s] -c> F<configfile>

B<rmexp-local -l [-m] [-s] -c> F<configfile>

B<rmexp-local --help|-?|--man>

 Options:
       -a               include all available backups in the report
       -d               print performed actions
       -c               configuration file name
       -l               list backups and exit
       -m               mount/unmount file system (rmexp-local only)
       -n               dry run
       -s               supress report if no warnings

       --help -?         brief help message
       --man             full documentation

=cut
